### ISSUE TITLE
Add Admin-On-Rest/Searchkit for Material UI and React.js client

### ISSUE THREAD

**Issue by roscopecoltran** [aio-libs/aiohttp_admin#218]
Hi guys,

Hope you are all well !

I was giving a try to aio-libs and I saw that ng-admin was integrated but it would be awesome and more interesting to add, from the same authors, admin-on-rest for a maetrial ui and reactjs version of the admin interface. ( [link](  https://github.com/marmelab/ng-admin#looking-for-a-material-ui--reactjs-version)). It would fit greatly also with https://github.com/searchkit/searchkit.

Some others related links that could fit perfectly with aio-libs:
- https://github.com/marmelab/admin-on-rest-demo
- https://github.com/marmelab/admin-on-rest
- https://github.com/marmelab/aor-dependent-input
- https://github.com/marmelab/aor-realtime
- https://github.com/marmelab/admin-on-rest-graphql-demo

Can you estimate how complicated it would be ? Have you already discussed that ?

Have a great day !

Cheers,
Richard

**Comment by jettify** [comment]
Thanks, I am aware of that projects, I have plans to move to `https://github.com/marmelab/admin-on-rest`, but no ETA moving there. PRs are welcome

**Comment by jettify** [comment]
see also https://github.com/aio-libs/aiohttp_admin/issues/20
