### ISSUE TITLE
SimpleType modifies value during validation

### ISSUE THREAD

**Issue by thenx** [aio-libs/aiohttp_admin#260]
`SimpleType` is defined as `t.Int | t.Bool | t.String | t.Float` which is used to validate ListQuery and Filters, in particular. During this validation it converts int-like strings to int. Later the filters are created with respect to collection schema. The value gets checked again but it is not string anymore which results in an error.

So a quick example of this error: you have a string column and you are trying to use int-like value in a filter.

There's a related [trafaret issue](https://github.com/Deepwalker/trafaret_forked/issues/69). Usage of newly-introduced Raw-types is suggested.

**Comment by jettify** [comment]
Good point, would you like to submit PR?
