### ISSUE TITLE
trafaret.DataError's method as_dict may return string

### ISSUE THREAD

**Issue by thenx** [aio-libs/aiohttp_admin#261]
This results in exceptions during passing validation errors to frontend in util.py and mongo_utils.py (lines with `**exc.as_dict()`)

There's also a related [trafaret issue](https://github.com/Deepwalker/trafaret_forked/issues/68) but currently trafaret may return strings so maybe aiohttp_admin should take this into account.

**Comment by jettify** [comment]
Thanks for heads-up!

**Comment by jettify** [comment]
fixed in https://github.com/aio-libs/aiohttp_admin/pull/266
