### ISSUE TITLE
Move from docker machine to just docker

### ISSUE THREAD

**Issue by gyermolenko** [aio-libs/aiohttp_admin#327]
`Machine was the only way to run Docker on Mac or Windows previous to Docker v1.12.` (from [the docs](https://docs.docker.com/machine/overview/))

I would like to try and switch from docker machine to just docker. 
- it is default 
- even though I tried to run tests on mac - I had some troubles switching
- currently `DOCKER_MACHINE_IP` option is spread in places it shouldn't be (e.g. [polls app](https://github.com/aio-libs/aiohttp_admin/blob/725257eec9bc4da9f94b839c2ae7d277e3a89e69/demos/polls/aiohttpdemo_polls/utils.py#L14) it overrides host from config)

**Comment by jettify** [comment]
👍 good idea, when I started docker-machine was way to go
