### ISSUE TITLE
Why the configuration file uses JavaScript

### ISSUE THREAD

**Issue by AlphaFase** [aio-libs/aiohttp_admin#380]
The configuration file is written in JavaScript. Are you kidding me? Why developers are hard to be developers?

two two Three， two two Three， six six six

**Comment by Arfey** [comment]
`aiohttp admin` automatically generates a rest api for` ng admin`. U can create its own ui, and it's very simple. We are trying to create admin without js config, but now it's not ready.

**Comment by jettify** [comment]
We are not kidding anyone if you see better and more efficient ways to do things please create PR and help us move the project forward.
