### ISSUE TITLE
when is the contrib folder hitting upstream pypi package?

### ISSUE THREAD

**Issue by japrogramer** [aio-libs/aiohttp_admin#388]
Hello some of the demos on this repo reference
 the aiohttp_admin.contrib module
which is not available in vs 0.0.3.
I would like to follow along with the examples using the pypi package

**Comment by jettify** [comment]
Sorry work still in slow progress :) once we can have something more stable we will create new release

**Comment by japrogramer** [comment]
ah, ok .. any idea what the time frame for the next release will be?
