### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sad-boy-uoa** [aio-libs/aiohttp_admin#450]
Hi there, when can I expect a new release of the source code?

**Comment by Arfey** [comment]
What, exactly, do you need?)

**Comment by sad-boy-uoa** [comment]
Other than all of the library updates and patches, the react admin.

**Comment by Arfey** [comment]
The experiment with react admin was bad and i think we will remove it. So, now we will not do release.

**Comment by sad-boy-uoa** [comment]
So you'll roll back the react changes but still keep the package updates and re-release that?

**Comment by Arfey** [comment]
Maybe. But not now.
If u want to use a new patches u can install this library from GitHub.

```
pip install git+https://github.com/aio-libs/aiohttp_admin.git
```
