### ISSUE TITLE
Improve login page

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp_admin#51]
1) Handle connection error, with proper message instead of popup
2) Handle 401 error with proper message
3) Make js/css code clean (https://github.com/aio-libs/aiohttp_admin/blob/master/aiohttp_admin/templates/login.html)

To run demo follow instructions here: https://github.com/aio-libs/aiohttp_admin/blob/master/demos/motortwit/README.rst

@goliney could you take a look?

**Comment by goliney** [comment]
@jettify I'm on it
